sudo: required
services:
  - docker

before_install:
  - docker build -t praveshbaloni/client-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true praveshbaloni/client-test npm run test

after_success:
  - docker build -t praveshbaloni/multi-client ./client
  - docker build -t praveshbaloni/multi-nginx ./nginx
  - docker build -t praveshbaloni/multi-server ./server
  - docker build -t praveshbaloni/multi-worker ./worker
  # docker log in
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push image to docker hub
  - docker push praveshbaloni/multi-client
  - docker push praveshbaloni/multi-nginx
  - docker push praveshbaloni/multi-server
  - docker push praveshbaloni/multi-worker